const CREATE_GAME_SOCKET = 'CREATE_GAME_SOCKET';
const NEW_PERSON = 'NEW_PERSON';
const DEL_GAME = 'DEL_GAME';
const START_GAME_SOCKET = 'START_GAME_SOCKET';
const ROLL_DICE_SOCKET = 'ROLL_DICE_SOCKET';

module.exports = {
  CREATE_GAME_SOCKET,
  NEW_PERSON,
  DEL_GAME,
  START_GAME_SOCKET,
  ROLL_DICE_SOCKET
};
