'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Streets', [
      {
        boardid: 1,
        special: 'null',
        corner: false,
        name: 'ЖИТНАЯ УЛ.',
        cost: 60,
        color: 'brown',
        maxlevel: 7,
        full: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 2,
        special: 'null',
        corner: false,
        name: 'ОБЩЕСТВЕННАЯ КАЗНА',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 3,
        special: 'null',
        corner: false,
        name: 'НАГАТИНСКАЯ УЛ.',
        cost: 60,
        color: 'brown',
        maxlevel: 7,
        full: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 4,
        special: 'null',
        corner: false,
        name: 'ПЛОТИ НАЛОГГ',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 5,
        special: 'train',
        corner: false,
        name: 'РИЖСКАЯ ЖД',
        cost: 200,
        maxlevel: 4,
        full: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 6,
        special: 'null',
        corner: false,
        name: 'ВАРШАВСКОЕ ШОССЕ',
        cost: 100,
        color: 'rgb(6, 136, 243);',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 7,
        special: 'null',
        corner: false,
        name: 'ШАНС',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 8,
        special: 'null',
        corner: false,
        name: 'ОГАРЕВА',
        cost: 100,
        color: 'rgb(6, 136, 243);',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 9,
        special: 'null',
        corner: false,
        name: 'ПЕРВАЯ ПАРКОВАЯ',
        cost: 120,
        color: 'rgb(6, 136, 243);',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 10,
        special: 'jail',
        corner: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 11,
        special: 'null',
        corner: false,
        name: 'ПОЛЯНКА',
        cost: 140,
        color: 'rgb(236, 34, 102);',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 12,
        special: 'null',
        corner: false,
        name: 'ЭЛЕКТРОСТАНЦИЯ',
        cost: 150,
        maxlevel: 2,
        full: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 13,
        special: 'null',
        corner: false,
        name: 'СРЕТЕНКА',
        cost: 140,
        color: 'rgb(236, 34, 102);',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 14,
        special: 'null',
        corner: false,
        name: 'РОСТОВСКАЯ НАБ',
        cost: 160,
        color: 'rgb(236, 34, 102);',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 15,
        special: 'null',
        corner: false,
        name: 'КУРСКАЯ ЖД',
        cost: 200,
        color: 'train',
        maxlevel: 4,
        full: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 16,
        special: 'null',
        corner: false,
        name: 'РЯЗАНСКИИЙ ПРОСПЕКТ',
        cost: 180,
        color: 'orange',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 17,
        special: 'null',
        corner: false,
        name: 'ОБЩЕСТВЕННАЯ КАЗНА',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 18,
        special: 'null',
        corner: false,
        name: 'ВАВИЛОВА',
        cost: 180,
        color: 'orange',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 19,
        special: 'null',
        corner: false,
        name: 'РУБЛЕВСКОЕ ШОССЕ',
        cost: 200,
        color: 'orange',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 20,
        special: 'parking',
        corner: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 21,
        special: 'null',
        corner: false,
        name: 'ТВЕРСКАЯ',
        cost: 220,
        color: 'red',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 21,
        special: 'null',
        corner: false,
        name: 'ШАНС',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 23,
        special: 'null',
        corner: false,
        name: 'ПУШСКИНСКАЯ',
        cost: 220,
        color: 'red',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 24,
        special: 'null',
        corner: false,
        name: 'ПЛОЩАДЬ МАЯКОВСКОГО',
        cost: 240,
        color: 'red',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 25,
        special: 'train',
        corner: false,
        name: 'КАЗАНСКАЯ ЖД',
        cost: 200,
        color: 'train',
        maxlevel: 4,
        full: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 26,
        special: 'null',
        corner: false,
        name: 'ГРУЗИИНСКИЙ ВАЛ',
        cost: 260,
        color: 'yellow',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 27,
        special: 'null',
        corner: false,
        name: 'ЧАЙУОВСКОГО',
        cost: 260,
        color: 'yellow',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 28,
        special: 'null',
        corner: false,
        name: 'ВОДОПРОВОД',
        cost: 150,
        maxlevel: 2,
        full: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 29,
        special: 'null',
        corner: false,
        name: 'СМОЛЕНСКАЯ ПЛОЩАДЬ',
        cost: 280,
        color: 'yellow',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 30,
        special: 'tojail',
        corner: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 31,
        special: 'null',
        corner: false,
        name: 'ЩУСЕВА',
        cost: 300,
        color: 'green',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 32,
        special: 'null',
        corner: false,
        name: 'ГОГОЛЕВСКИЙ БУЛЬВАР',
        cost: 300,
        color: 'green',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 33,
        special: 'null',
        corner: false,
        name: 'ОБЩЕСТВЕННАЯ КАЗНА',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 34,
        special: 'null',
        corner: false,
        name: 'КУТУЗОВСКИЙ ПРОСПЕКТ',
        cost: 320,
        color: 'green',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 35,
        special: 'null',
        corner: false,
        name: 'ЛЕНЕНГРАДСКАЯ ЖД',
        cost: 200,
        color: 'train',
        maxlevel: 4,
        full: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 36,
        special: 'null',
        corner: false,
        name: 'ШАНС',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 37,
        special: 'null',
        corner: false,
        name: 'МАЛАЯ БРОННАЯ',
        cost: 350,
        color: 'blue',
        maxlevel: 7,
        full: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 38,
        special: 'null',
        corner: false,
        name: 'ПЛОТИ!',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 39,
        special: 'null',
        corner: false,
        name: 'АРБАТ',
        cost: 400,
        color: 'blue',
        maxlevel: 7,
        full: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 0,
        special: 'start',
        corner: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {},
};
