'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Streets', [
      {
        name: 'ЖИТНАЯ УЛ.',
        cost: '60k',
        color: 'brown',
        maxlevel: 7,
        full: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'НАГАТИНСКАЯ УЛ.',
        cost: '60k',
        color: 'brown',
        maxlevel: 7,
        full: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'РИЖСКАЯ ЖД',
        cost: '200k',
        color: 'train',
        maxlevel: 4,
        full: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ВАРШАВСКОЕ ШОССЕ',
        cost: '100k',
        color: 'rgb(6, 136, 243);',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ОГАРЕВА',
        cost: '100k',
        color: 'rgb(6, 136, 243);',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ПЕРВАЯ ПАРКОВАЯ',
        cost: '120k',
        color: 'rgb(6, 136, 243);',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ПОЛЯНКА',
        cost: '140k',
        color: 'rgb(236, 34, 102);',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ЭЛЕКТРОСТАНЦИЯ',
        cost: '150k',
        color: '',
        maxlevel: 2,
        full: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'СРЕТЕНКА',
        cost: '140k',
        color: 'rgb(236, 34, 102);',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'РОСТОВСКАЯ НАБ',
        cost: '160k',
        color: 'rgb(236, 34, 102);',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'КУРСКАЯ ЖД',
        cost: '200k',
        color: 'train',
        maxlevel: 4,
        full: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ВАРШАВСКОЕ ШОССЕ',
        cost: '180k',
        color: 'orange',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'РОСТОВСКАЯ НАБ',
        cost: '180k',
        color: 'orange',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'РУБЛЕВСКОЕ ШОССЕ',
        cost: '200k',
        color: 'orange',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ТВЕРСКАЯ',
        cost: '220k',
        color: 'red',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ПУШСКИНСКАЯ',
        cost: '220k',
        color: 'red',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ПЛОЩАДЬ МАЯКОВСКОГО',
        cost: '240k',
        color: 'red',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'КАЗАНСКАЯ ЖД',
        cost: '200k',
        color: 'train',
        maxlevel: 4,
        full: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ГРУЗИИНСКИЙ ВАЛ',
        cost: '260k',
        color: 'yellow',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ЧАЙУОВСКОГО',
        cost: '260k',
        color: 'yellow',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ВОДОПРОВОД',
        cost: '150k',
        color: '',
        maxlevel: 2,
        full: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'СМОЛЕНСКАЯ ПЛОЩАДЬ',
        cost: '280k',
        color: 'yellow',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ЩУСЕВА',
        cost: '300k',
        color: 'green',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ГОГОЛЕВСКИЙ БУЛЬВАР',
        cost: '300k',
        color: 'green',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'КУТУЗОВСКИЙ ПРОСПЕКТ',
        cost: '320k',
        color: 'green',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ЛЕНЕНГРАДСКАЯ ЖД',
        cost: '200k',
        color: 'train',
        maxlevel: 4,
        full: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'МАЛАЯ БРОННАЯ',
        cost: '350k',
        color: 'blue',
        maxlevel: 7,
        full: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: 'ЧАЙУОВСКОГО',
        cost: '400k',
        color: 'blue',
        maxlevel: 7,
        full: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      
    ]);
  },

  down: async (queryInterface, Sequelize) => {},
};
