'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Streets', [
      {
        boardid: 1,
        special: 'null',
        corner: false,
        name: 'житная ул.',
        cost: 60,
        color: 'brown',
        maxlevel: 7,
        full: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 2,
        special: 'null',
        corner: false,
        name: 'общественная казна',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 3,
        special: 'null',
        corner: false,
        name: 'нагатинска ул.',
        cost: 60,
        color: 'brown',
        maxlevel: 7,
        full: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 4,
        special: 'null',
        corner: false,
        name: 'плоти налогг',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 5,
        special: 'train',
        corner: false,
        name: 'рижская жд',
        cost: 200,
        maxlevel: 4,
        full: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 6,
        special: 'null',
        corner: false,
        name: 'варшавское шоссе',
        cost: 100,
        color: 'rgb(6, 136, 243);',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 7,
        special: 'null',
        corner: false,
        name: 'шанс',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 8,
        special: 'null',
        corner: false,
        name: 'огарева',
        cost: 100,
        color: 'rgb(6, 136, 243);',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 9,
        special: 'null',
        corner: false,
        name: 'первая парковая',
        cost: 120,
        color: 'rgb(6, 136, 243);',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 10,
        special: 'jail',
        corner: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 11,
        special: 'null',
        corner: false,
        name: 'полянка',
        cost: 140,
        color: 'rgb(236, 34, 102);',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 12,
        special: 'null',
        corner: false,
        name: 'электростанция',
        cost: 150,
        maxlevel: 2,
        full: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 13,
        special: 'null',
        corner: false,
        name: 'сретенка',
        cost: 140,
        color: 'rgb(236, 34, 102);',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 14,
        special: 'null',
        corner: false,
        name: 'ростовская наб',
        cost: 160,
        color: 'rgb(236, 34, 102);',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 15,
        special: 'train',
        corner: false,
        name: 'курская жд',
        cost: 200,
        maxlevel: 4,
        full: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 16,
        special: 'null',
        corner: false,
        name: 'рязанский проспект',
        cost: 180,
        color: 'orange',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 17,
        special: 'null',
        corner: false,
        name: 'общественная казна',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 18,
        special: 'null',
        corner: false,
        name: 'вавилова',
        cost: 180,
        color: 'orange',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 19,
        special: 'null',
        corner: false,
        name: 'рублевское шоссе',
        cost: 200,
        color: 'orange',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 20,
        special: 'parking',
        corner: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 21,
        special: 'null',
        corner: false,
        name: 'тверская',
        cost: 220,
        color: 'red',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 22,
        special: 'null',
        corner: false,
        name: 'шанс',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 23,
        special: 'null',
        corner: false,
        name: 'пушкинская',
        cost: 220,
        color: 'red',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 24,
        special: 'null',
        corner: false,
        name: 'площадь маяковского',
        cost: 240,
        color: 'red',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 25,
        special: 'train',
        corner: false,
        name: 'казанская жд',
        cost: 200,
        maxlevel: 4,
        full: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 26,
        special: 'null',
        corner: false,
        name: 'грузинский вал',
        cost: 260,
        color: 'yellow',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 27,
        special: 'null',
        corner: false,
        name: 'новинскиий бульвар',
        cost: 260,
        color: 'yellow',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 28,
        special: 'null',
        corner: false,
        name: 'водопровод',
        cost: 150,
        maxlevel: 2,
        full: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 29,
        special: 'null',
        corner: false,
        name: 'смоленская площадь',
        cost: 280,
        color: 'yellow',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 30,
        special: 'tojail',
        corner: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 31,
        special: 'null',
        corner: false,
        name: 'щусева',
        cost: 300,
        color: 'green',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 32,
        special: 'null',
        corner: false,
        name: 'гоголевский бульвар',
        cost: 300,
        color: 'green',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 33,
        special: 'null',
        corner: false,
        name: 'общественная казна',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 34,
        special: 'null',
        corner: false,
        name: 'кутузовский проспект',
        cost: 320,
        color: 'green',
        maxlevel: 7,
        full: 3,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 35,
        special: 'train',
        corner: false,
        name: 'лененградская жд',
        cost: 200,
        maxlevel: 4,
        full: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 36,
        special: 'null',
        corner: false,
        name: 'шанс на повтор',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 37,
        special: 'null',
        corner: false,
        name: 'малая бронная',
        cost: 350,
        color: 'blue',
        maxlevel: 7,
        full: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 38,
        special: 'null',
        corner: false,
        name: 'уборки стола',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 39,
        special: 'null',
        corner: false,
        name: 'арбат',
        cost: 400,
        color: 'blue',
        maxlevel: 7,
        full: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        boardid: 0,
        special: 'start',
        corner: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {},
};
