'use strict';

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert('Dohods', [
      {
        streetid: 1,
        level: 1,
        value: 2,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 1,
        level: 2,
        value: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 1,
        level: 3,
        value: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 1,
        level: 4,
        value: 30,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 1,
        level: 5,
        value: 90,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 1,
        level: 6,
        value: 160,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 1,
        level: 7,
        value: 250,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 3,
        level: 1,
        value: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 3,
        level: 2,
        value: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 3,
        level: 3,
        value: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 3,
        level: 4,
        value: 60,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 3,
        level: 5,
        value: 180,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 3,
        level: 6,
        value: 320,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 3,
        level: 7,
        value: 450,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 5,
        level: 1,
        value: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 5,
        level: 2,
        value: 50,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 5,
        level: 3,
        value: 100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 5,
        level: 4,
        value: 200,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 6,
        level: 1,
        value: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 6,
        level: 2,
        value: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 6,
        level: 3,
        value: 30,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 6,
        level: 4,
        value: 90,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 6,
        level: 5,
        value: 270,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 6,
        level: 6,
        value: 400,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 6,
        level: 7,
        value: 550,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 8,
        level: 1,
        value: 6,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 8,
        level: 2,
        value: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 8,
        level: 3,
        value: 30,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 8,
        level: 4,
        value: 90,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 8,
        level: 5,
        value: 270,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 8,
        level: 6,
        value: 400,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 8,
        level: 7,
        value: 550,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 9,
        level: 1,
        value: 8,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 9,
        level: 2,
        value: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 9,
        level: 3,
        value: 40,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 9,
        level: 4,
        value: 100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 9,
        level: 5,
        value: 300,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 9,
        level: 6,
        value: 450,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 9,
        level: 7,
        value: 600,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 11,
        level: 1,
        value: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 11,
        level: 2,
        value: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 11,
        level: 3,
        value: 50,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 11,
        level: 4,
        value: 150,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 11,
        level: 5,
        value: 450,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 11,
        level: 6,
        value: 625,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 11,
        level: 7,
        value: 750,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 12,
        level: 1,
        value: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 12,
        level: 2,
        value: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 13,
        level: 1,
        value: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 13,
        level: 2,
        value: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 13,
        level: 3,
        value: 50,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 13,
        level: 4,
        value: 150,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 13,
        level: 5,
        value: 450,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 13,
        level: 6,
        value: 625,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 13,
        level: 7,
        value: 750,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 14,
        level: 1,
        value: 12,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 14,
        level: 2,
        value: 24,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 14,
        level: 3,
        value: 60,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 14,
        level: 4,
        value: 180,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 14,
        level: 5,
        value: 500,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 14,
        level: 6,
        value: 700,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 14,
        level: 7,
        value: 900,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 15,
        level: 1,
        value: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 15,
        level: 2,
        value: 50,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 15,
        level: 3,
        value: 100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 15,
        level: 4,
        value: 200,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 16,
        level: 1,
        value: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 16,
        level: 2,
        value: 28,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 16,
        level: 3,
        value: 70,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 16,
        level: 4,
        value: 200,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 16,
        level: 5,
        value: 550,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 16,
        level: 6,
        value: 750,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 16,
        level: 7,
        value: 950,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 18,
        level: 1,
        value: 14,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 18,
        level: 2,
        value: 28,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 18,
        level: 3,
        value: 70,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 18,
        level: 4,
        value: 200,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 18,
        level: 5,
        value: 550,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 18,
        level: 6,
        value: 750,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 18,
        level: 7,
        value: 950,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 19,
        level: 1,
        value: 16,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 19,
        level: 2,
        value: 32,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 19,
        level: 3,
        value: 80,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 19,
        level: 4,
        value: 220,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 19,
        level: 5,
        value: 600,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 19,
        level: 6,
        value: 800,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 19,
        level: 7,
        value: 1000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 21,
        level: 1,
        value: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 21,
        level: 2,
        value: 36,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 21,
        level: 3,
        value: 90,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 21,
        level: 4,
        value: 250,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 21,
        level: 5,
        value: 700,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 21,
        level: 6,
        value: 875,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 21,
        level: 7,
        value: 1050,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 23,
        level: 1,
        value: 18,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 23,
        level: 2,
        value: 36,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 23,
        level: 3,
        value: 90,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 23,
        level: 4,
        value: 250,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 23,
        level: 5,
        value: 700,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 23,
        level: 6,
        value: 875,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 23,
        level: 7,
        value: 1050,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 24,
        level: 1,
        value: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 24,
        level: 2,
        value: 40,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 24,
        level: 3,
        value: 100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 24,
        level: 4,
        value: 300,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 24,
        level: 5,
        value: 750,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 24,
        level: 6,
        value: 975,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 24,
        level: 7,
        value: 1100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 25,
        level: 1,
        value: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 25,
        level: 2,
        value: 50,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 25,
        level: 3,
        value: 100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 25,
        level: 4,
        value: 200,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 26,
        level: 1,
        value: 22,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 26,
        level: 2,
        value: 44,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 26,
        level: 3,
        value: 110,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 26,
        level: 4,
        value: 330,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 26,
        level: 5,
        value: 800,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 26,
        level: 6,
        value: 975,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 26,
        level: 7,
        value: 1150,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 27,
        level: 1,
        value: 22,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 27,
        level: 2,
        value: 44,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 27,
        level: 3,
        value: 110,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 27,
        level: 4,
        value: 330,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 27,
        level: 5,
        value: 800,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 27,
        level: 6,
        value: 975,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 27,
        level: 7,
        value: 1150,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 28,
        level: 1,
        value: 4,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 28,
        level: 2,
        value: 10,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 29,
        level: 1,
        value: 24,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 29,
        level: 2,
        value: 48,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 29,
        level: 3,
        value: 120,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 29,
        level: 4,
        value: 360,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 29,
        level: 5,
        value: 850,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 29,
        level: 6,
        value: 1025,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 29,
        level: 7,
        value: 1200,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        streetid: 31,
        level: 1,
        value: 26,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 31,
        level: 2,
        value: 52,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 31,
        level: 3,
        value: 130,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 31,
        level: 4,
        value: 390,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 31,
        level: 5,
        value: 900,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 31,
        level: 6,
        value: 1100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 31,
        level: 7,
        value: 1275,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 32,
        level: 1,
        value: 26,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 32,
        level: 2,
        value: 52,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 32,
        level: 3,
        value: 130,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 32,
        level: 4,
        value: 390,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 32,
        level: 5,
        value: 900,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 32,
        level: 6,
        value: 1100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 32,
        level: 7,
        value: 1275,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 34,
        level: 1,
        value: 28,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 34,
        level: 2,
        value: 56,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 34,
        level: 3,
        value: 150,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 34,
        level: 4,
        value: 450,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 34,
        level: 5,
        value: 1000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 34,
        level: 6,
        value: 1200,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 34,
        level: 7,
        value: 1400,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 35,
        level: 1,
        value: 25,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 35,
        level: 2,
        value: 50,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 35,
        level: 3,
        value: 100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 35,
        level: 4,
        value: 200,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        streetid: 37,
        level: 1,
        value: 35,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 37,
        level: 2,
        value: 70,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 37,
        level: 3,
        value: 175,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 37,
        level: 4,
        value: 500,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 37,
        level: 5,
        value: 1100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 37,
        level: 6,
        value: 1300,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 37,
        level: 7,
        value: 1500,
        createdAt: new Date(),
        updatedAt: new Date(),
      },

      {
        streetid: 39,
        level: 1,
        value: 50,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 39,
        level: 2,
        value: 100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 39,
        level: 3,
        value: 200,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 39,
        level: 4,
        value: 600,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 39,
        level: 5,
        value: 1400,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 39,
        level: 6,
        value: 1700,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        streetid: 39,
        level: 7,
        value: 2000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  down: async (queryInterface, Sequelize) => {

  },
};
