export const START_GAME_SOCKET = 'START_GAME_SOCKET';
export const CREATE_GAME_SOCKET = 'CREATE_GAME_SOCKET';
export const GET_GAME_USERS_SOCKET = 'GET_GAME_USERS_SOCKET';
export const NEW_PERSON_SOCKET = 'NEW_PERSON_SOCKET';
