export const START_GAME_SOCKET = 'START_GAME_SOCKET';
export const CREATE_GAME_SOCKET = 'CREATE_GAME_SOCKET';
export const GET_GAME_USERS_SOCKET = 'GET_GAME_USERS_SOCKET';
export const ROLL_DICE_SOCKET = 'ROLL_DICE_SOCKET';
export const TURN_SOCKET = 'TURN_SOCKET';
export const GET_CARD_USER_SOCKET = 'GET_CARD_USER_SOCKET';

